# For Java 8, try this
# FROM openjdk:8-jdk-alpine

# For Java 11, try this
#FROM adoptopenjdk/openjdk11:alpine-jre
FROM openjdk

# Refer to Maven build -> finalName
ARG JAR_FILE=target/CrudHash-Back-0.0.1.jar

# cd /opt/app
WORKDIR /app

# cp target/spring-boot-web.jar /opt/app/app.jar
COPY ${JAR_FILE} CrudHash-Back-0.0.1.jar

# java -jar /opt/app/app.jar
ENTRYPOINT ["java","-jar","CrudHash-Back-0.0.1.jar"]